# Generated automatically from Makefile.in by config.pl.
# KDE tags expanded automatically by am_edit - $Revision: 1.1 $ 
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

####### kdevelop will overwrite this part!!! (begin)##########


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
VPATH = .
prefix = /opt/kde2
exec_prefix = ${prefix}
#>- 
bindir = ${exec_prefix}/bin
#>+ 3
DEPDIR = .deps

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/knetswitch
pkglibdir = $(libdir)/knetswitch
pkgincludedir = $(includedir)/knetswitch

top_builddir = ..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/ginstall -c -p
INSTALL_PROGRAM = ${INSTALL} $(INSTALL_STRIP_FLAG) $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-linux-gnu
build_triplet = i686-pc-linux-gnu
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_alias = i686-pc-linux-gnu
target_triplet = i686-pc-linux-gnu
ARTSCCONFIG = /opt/kde2/bin/artsc-config
AS = @AS@
AUTODIRS = 
CC = gcc
CONF_FILES =  $(top_srcdir)/./admin/configure.in.min $(top_srcdir)/configure.in.in
CPP = gcc -E
CXX = c++
CXXCPP = c++ -E
DCOPIDL = /opt/kde2/bin/dcopidl
DCOPIDL2CPP = /opt/kde2/bin/dcopidl2cpp
DCOP_DEPENDENCIES = $(DCOPIDL)
DLLTOOL = @DLLTOOL@
DPMSINC = @DPMSINC@
DPMSLIB = @DPMSLIB@
EXEEXT = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GLINC = @GLINC@
GLLIB = @GLLIB@
GMSGFMT = /usr/bin/msgfmt
IDL = @IDL@
IDL_DEPENDENCIES = @IDL_DEPENDENCIES@
JAR = @JAR@
JAVAC = @JAVAC@
JAVAH = @JAVAH@
JVMLIBS = @JVMLIBS@
KDECONFIG = /opt/kde2/bin/kde-config
KDE_CXXFLAGS = 
KDE_EXTRA_RPATH = 
KDE_INCLUDES = -I/opt/kde2/include
KDE_LDFLAGS = -L/opt/kde2/lib
KDE_PLUGIN = -avoid-version -module -no-undefined $(KDE_RPATH)
KDE_RPATH = -R $(kde_libraries) -R $(x_libraries)
KDE_USE_CLOSURE_FALSE = #
KDE_USE_CLOSURE_TRUE = 
KDE_USE_FINAL_FALSE = 
KDE_USE_FINAL_TRUE = #
KDE_XSL_STYLESHEET = /opt/kde2/share/apps/ksgmltools2/customization/kde-chunk.xsl
LIBCOMPAT = 
LIBCRYPT = -lcrypt
LIBDL = -ldl
LIBGEN = @LIBGEN@
LIBJPEG = -ljpeg
LIBMICO = @LIBMICO@
LIBOBJS = @LIBOBJS@
LIBPNG = -lpng -lz -lm
LIBPTHREAD = @LIBPTHREAD@
LIBPYTHON = @LIBPYTHON@
LIBQIMGIO = @LIBQIMGIO@
LIBRESOLV = 
LIBSHADOW = @LIBSHADOW@
LIBSM = -lSM -lICE
LIBSOCKET = 
LIBTIFF = @LIBTIFF@
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBUCB = 
LIBUTIL = -lutil
LIBXINERAMA = 
LIBZ = -lz
LIB_KAB = -lkab
LIB_KDECORE = -lkdecore
LIB_KDEUI = -lkdeui
LIB_KFILE = -lkfile
LIB_KFM = 
LIB_KFORMULA = -lkformula
LIB_KHTML = -lkhtml
LIB_KIMGIO = @LIB_KIMGIO@
LIB_KIO = -lkio
LIB_KPARTS = -lkparts
LIB_KSPELL = -lkspell
LIB_KSYCOCA = -lksycoca
LIB_KWRITE = -lkwrite
LIB_QT = -lqt $(LIBPNG) $(LIBJPEG) -lXext $(LIB_X11) $(LIBSM)
LIB_SMB = -lsmb
LIB_X11 = -lX11 $(LIBSOCKET)
LN_S = ln -s
MAKEINFO = makeinfo
MCOPIDL = /opt/kde2/bin/mcopidl
MEINPROC = /opt/kde2/bin/meinproc
MICO_INCLUDES = @MICO_INCLUDES@
MICO_LDFLAGS = @MICO_LDFLAGS@
MOC = /usr/local/qt/bin/moc
MSGFMT = /usr/bin/msgfmt
NOOPT_CXXFLAGS =  -g3 -Wall -fno-exceptions -fno-check-new
NOREPO = -fno-repo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = knetswitch
PAMLIBS = @PAMLIBS@
PASSWDLIBS = @PASSWDLIBS@
PYTHONINC = @PYTHONINC@
PYTHONLIB = @PYTHONLIB@
PYTHONMODDIR = @PYTHONMODDIR@
QT_INCLUDES = -I/usr/local/qt/include
QT_LDFLAGS = 
RANLIB = ranlib
REPO = -frepo
SETUIDFLAGS = @SETUIDFLAGS@
STRIP = strip
TOPSUBDIRS =  doc knetswitch po
UIC = /usr/local/qt/bin/uic
USER_INCLUDES = 
USER_LDFLAGS = 
USE_EXCEPTIONS = -fexceptions
USE_RTTI = 
USE_THREADS = @USE_THREADS@
VERSION = 0.1
XGETTEXT = /usr/bin/xgettext
XPMINC = @XPMINC@
XPMLIB = @XPMLIB@
X_EXTRA_LIBS = 
X_INCLUDES = -I/usr/X11R6/include
X_LDFLAGS = -L/usr/X11R6/lib
X_PRE_LIBS = 
all_includes = -I/opt/kde2/include -I/usr/local/qt/include -I/usr/X11R6/include 
all_libraries = -L/usr/X11R6/lib -L/opt/kde2/lib 
idldir = @idldir@
jni_includes = @jni_includes@
kde_appsdir = ${prefix}/share/applnk
kde_bindir = ${exec_prefix}/bin
kde_confdir = ${prefix}/share/config
kde_datadir = ${prefix}/share/apps
kde_htmldir = ${prefix}/share/doc/HTML
kde_icondir = ${prefix}/share/icons
kde_includes = /opt/kde2/include
kde_libraries = /opt/kde2/lib
kde_libs_htmldir = /opt/kde2/share/doc/HTML
kde_libs_prefix = /opt/kde2
kde_locale = ${prefix}/share/locale
kde_mimedir = ${prefix}/share/mimelnk
kde_moduledir = ${exec_prefix}/lib/kde2
kde_servicesdir = ${prefix}/share/services
kde_servicetypesdir = ${prefix}/share/servicetypes
kde_sounddir = ${prefix}/share/sounds
kde_templatesdir = ${prefix}/share/templates
kde_wallpaperdir = ${prefix}/share/wallpapers
micodir = @micodir@
qt_includes = /usr/local/qt/include
qt_libraries = 
x_includes = /usr/X11R6/include
x_libraries = /usr/X11R6/lib

kde_module_LTLIBRARIES = libkcm_knetswitch.la

INCLUDES = $(all_includes)

LDFLAGS = 

#>- libkcm_knetswitch_la_METASOURCES = AUTO

#>- libkcm_knetswitch_la_SOURCES = profilewidget.cpp profiletab.ui knetswitch.cpp 
#>+ 1
libkcm_knetswitch_la_SOURCES=profilewidget.cpp  knetswitch.cpp  profiletab.cpp
libkcm_knetswitch_la_LIBADD = -lXext -lX11 $(LIB_QT) $(LIB_KDECORE) $(LIB_KDEUI) 

libkcm_knetswitch_la_LDFLAGS = -module $(KDE_PLUGIN)   

EXTRA_DIST = knetswitch.cpp knetswitch.h profiletab.ui profilewidget.cpp profilewidget.h 
mkinstalldirs = $(SHELL) $(top_srcdir)/admin/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
LTLIBRARIES =  $(kde_module_LTLIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I..
CPPFLAGS = 
LIBS = 
libkcm_knetswitch_la_DEPENDENCIES = 
#>- libkcm_knetswitch_la_OBJECTS =  profilewidget.lo knetswitch.lo
#>+ 5
libkcm_knetswitch_la_final_OBJECTS = libkcm_knetswitch_la.all_cpp.lo 
libkcm_knetswitch_la_nofinal_OBJECTS = profilewidget.lo knetswitch.lo profiletab.lo \
libkcm_knetswitch_la_meta_unload.lo 
libkcm_knetswitch_la_OBJECTS = $(libkcm_knetswitch_la_nofinal_OBJECTS)
#libkcm_knetswitch_la_OBJECTS = $(libkcm_knetswitch_la_final_OBJECTS)
CXXFLAGS = -O2 -O0 -g3 -Wall -fno-exceptions -fno-check-new
#>- CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 1
CXXCOMPILE = $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
#>- LTCXXCOMPILE = $(LIBTOOL) --mode=compile $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
#>+ 1
LTCXXCOMPILE = $(LIBTOOL) --mode=compile --tag=CXX $(CXX) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS)
CXXLD = $(CXX)
#>- CXXLINK = $(LIBTOOL) --mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(LDFLAGS) -o $@
#>+ 1
CXXLINK = $(LIBTOOL) --mode=link --tag=CXX $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(KDE_CXXFLAGS) $(LDFLAGS) -o $@
DIST_COMMON =  Makefile.am Makefile.in


#>- DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
#>+ 4
KDE_DIST=libkcm_knetswitch_la_meta_unload.cpp libkcm_knetswitch.la.closure knetswitch.desktop profiletab.h 

DISTFILES= $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST) $(KDE_DIST)


TAR = tar
GZIP_ENV = --best
#>- DEP_FILES =  .deps/knetswitch.P .deps/profilewidget.P
#>+ 4
#DEP_FILES =  $(DEPDIR)/profiletab.P $(DEPDIR)/libkcm_knetswitch_la_meta_unload.P  $(DEPDIR)/libkcm_knetswitch_la.all_cpp.P \
	  .deps/knetswitch.P .deps/profilewidget.P
DEP_FILES =  $(DEPDIR)/profiletab.P $(DEPDIR)/libkcm_knetswitch_la_meta_unload.P   .deps/knetswitch.P .deps/profilewidget.P

SOURCES = $(libkcm_knetswitch_la_SOURCES)
OBJECTS = $(libkcm_knetswitch_la_OBJECTS)

#>- all: all-redirect
#>+ 1
all: docs-am  all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .cpp .lo .o .obj .s
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
#>- 	cd $(top_srcdir) && $(AUTOMAKE) --gnu knetswitch/Makefile
#>+ 2
	cd $(top_srcdir) && $(AUTOMAKE) --gnu knetswitch/Makefile
	cd $(top_srcdir) && perl admin/am_edit knetswitch/Makefile.in

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-kde_moduleLTLIBRARIES:

clean-kde_moduleLTLIBRARIES:
	-test -z "$(kde_module_LTLIBRARIES)" || rm -f $(kde_module_LTLIBRARIES)

distclean-kde_moduleLTLIBRARIES:

maintainer-clean-kde_moduleLTLIBRARIES:

install-kde_moduleLTLIBRARIES: $(kde_module_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(kde_moduledir)
	@list='$(kde_module_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo "$(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(kde_moduledir)/$$p"; \
	    $(LIBTOOL)  --mode=install $(INSTALL) $$p $(DESTDIR)$(kde_moduledir)/$$p; \
	  else :; fi; \
	done

uninstall-kde_moduleLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(kde_module_LTLIBRARIES)'; for p in $$list; do \
	  $(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(kde_moduledir)/$$p; \
	done

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

#>- libkcm_knetswitch.la: $(libkcm_knetswitch_la_OBJECTS) $(libkcm_knetswitch_la_DEPENDENCIES)
#>+ 2
libkcm_knetswitch.la: libkcm_knetswitch.la.closure $(libkcm_knetswitch_la_OBJECTS) $(libkcm_knetswitch_la_DEPENDENCIES)
#libkcm_knetswitch.la: $(libkcm_knetswitch_la_OBJECTS) $(libkcm_knetswitch_la_DEPENDENCIES)
	$(CXXLINK) -rpath $(kde_moduledir) $(libkcm_knetswitch_la_LDFLAGS) $(libkcm_knetswitch_la_OBJECTS) $(libkcm_knetswitch_la_LIBADD) $(LIBS)
.cpp.o:
	$(CXXCOMPILE) -c $<
.cpp.obj:
	$(CXXCOMPILE) -c `cygpath -w $<`
.cpp.lo:
	$(LTCXXCOMPILE) -c $<

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = knetswitch

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu knetswitch/Makefile
#>- 	@for file in $(DISTFILES); do \
#>- 	  d=$(srcdir); \
#>- 	  if test -d $$d/$$file; then \
#>- 	    cp -pr $$/$$file $(distdir)/$$file; \
#>- 	  else \
#>- 	    test -f $(distdir)/$$file \
#>- 	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
#>- 	    || cp -p $$d/$$file $(distdir)/$$file || :; \
#>- 	  fi; \
#>- 	done
#>+ 10
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done

DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)

-include $(DEP_FILES)

mostlyclean-depend:

clean-depend:

distclean-depend:
	-rm -rf .deps

maintainer-clean-depend:

%.o: %.c
	@echo '$(COMPILE) -c $<'; \
	$(COMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-cp .deps/$(*F).pp .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm .deps/$(*F).pp

%.lo: %.c
	@echo '$(LTCOMPILE) -c $<'; \
	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
	  < .deps/$(*F).pp > .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm -f .deps/$(*F).pp

%.o: %.cpp
	@echo '$(CXXCOMPILE) -c $<'; \
	$(CXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-cp .deps/$(*F).pp .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm .deps/$(*F).pp

%.lo: %.cpp
	@echo '$(LTCXXCOMPILE) -c $<'; \
	$(LTCXXCOMPILE) -Wp,-MD,.deps/$(*F).pp -c $<
	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
	  < .deps/$(*F).pp > .deps/$(*F).P; \
	tr ' ' '\012' < .deps/$(*F).pp \
	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
	    >> .deps/$(*F).P; \
	rm -f .deps/$(*F).pp
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
#>- install-exec-am:
#>+ 1
install-exec-am: install-kde_moduleLTLIBRARIES
install-exec: install-exec-am

#>- install-data-am: install-kde_moduleLTLIBRARIES
#>+ 1
install-data-am:  
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-kde_moduleLTLIBRARIES
uninstall: uninstall-am
all-am: Makefile $(LTLIBRARIES)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(kde_moduledir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-kde_moduleLTLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags mostlyclean-depend \
		mostlyclean-generic

mostlyclean: mostlyclean-am

#>- clean-am:  clean-kde_moduleLTLIBRARIES clean-compile clean-libtool \
#>- 		clean-tags clean-depend clean-generic mostlyclean-am
#>+ 2
clean-am: clean-metasources clean-ui clean-closures clean-moc-classes clean-final   clean-kde_moduleLTLIBRARIES clean-compile clean-libtool \
		clean-tags clean-depend clean-generic mostlyclean-am

#>- clean: clean-am
#>+ 1
clean: kde-rpo-clean  clean-am

distclean-am:  distclean-kde_moduleLTLIBRARIES distclean-compile \
		distclean-libtool distclean-tags distclean-depend \
		distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-kde_moduleLTLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-depend \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-kde_moduleLTLIBRARIES \
distclean-kde_moduleLTLIBRARIES clean-kde_moduleLTLIBRARIES \
maintainer-clean-kde_moduleLTLIBRARIES uninstall-kde_moduleLTLIBRARIES \
install-kde_moduleLTLIBRARIES mostlyclean-compile distclean-compile \
clean-compile maintainer-clean-compile mostlyclean-libtool \
distclean-libtool clean-libtool maintainer-clean-libtool tags \
mostlyclean-tags distclean-tags clean-tags maintainer-clean-tags \
distdir mostlyclean-depend distclean-depend clean-depend \
maintainer-clean-depend info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-exec-am install-exec \
install-data-am install-data install-am install uninstall-am uninstall \
all-redirect all-am all installdirs mostlyclean-generic \
distclean-generic clean-generic maintainer-clean-generic clean \
mostlyclean distclean maintainer-clean


####### kdevelop will overwrite this part!!! (end)############
messages:
	$(XGETTEXT) $(libkcm_knetswitch_la_SOURCES) -o $(podir)/kcmknetswitch.pot

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:

#>+ 8
libkcm_knetswitch.la.closure: $(libkcm_knetswitch_la_OBJECTS) $(libkcm_knetswitch_la_DEPENDENCIES)
	@echo "int main() {return 0;}" > libkcm_knetswitch_la_closure.cpp
	@$(LTCXXCOMPILE) -c libkcm_knetswitch_la_closure.cpp
	@$(CXXLINK) libkcm_knetswitch_la_closure.lo $(libkcm_knetswitch_la_LDFLAGS) $(libkcm_knetswitch_la_OBJECTS) $(libkcm_knetswitch_la_LIBADD) $(LIBS)
	@rm -f libkcm_knetswitch_la_closure.* libkcm_knetswitch.la.closure
	@echo "timestamp" > libkcm_knetswitch.la.closure


#>+ 3
profiletab.moc: $(srcdir)/profiletab.h
	$(MOC) $(srcdir)/profiletab.h -o profiletab.moc

#>+ 3
knetswitch.moc: $(srcdir)/knetswitch.h
	$(MOC) $(srcdir)/knetswitch.h -o knetswitch.moc

#>+ 12
profiletab.cpp: $(srcdir)/profiletab.ui profiletab.h profiletab.moc
	rm -f profiletab.cpp
	echo '#include <klocale.h>' > profiletab.cpp
	$(UIC) -tr i18n -i profiletab.h $(srcdir)/profiletab.ui | sed -e "s,i18n( \"\" ),QString::null,g" >> profiletab.cpp || rm -f profiletab.cpp
	echo '#include "profiletab.moc"' >> profiletab.cpp

profiletab.h: $(srcdir)/profiletab.ui
	$(UIC) -o profiletab.h $(srcdir)/profiletab.ui

profiletab.moc: profiletab.h
	$(MOC) profiletab.h -o profiletab.moc

#>+ 3
clean-metasources:
	-rm -f  profiletab.moc knetswitch.moc

#>+ 4
clean-ui:
	-rm -f \
	profiletab.cpp profiletab.h profiletab.moc 

#>+ 3
clean-closures:
	-rm -f  libkcm_knetswitch.la.closure

#>+ 2
docs-am:

#>+ 5
force-reedit:
		cd $(top_srcdir) && $(AUTOMAKE) --gnu knetswitch/Makefile
	cd $(top_srcdir) && perl admin/am_edit knetswitch/Makefile.in


#>+ 10
libkcm_knetswitch_la_meta_unload.cpp:  profiletab.moc knetswitch.moc
	@echo 'creating libkcm_knetswitch_la_meta_unload.cpp'
	@-rm -f libkcm_knetswitch_la_meta_unload.cpp
	@echo 'static const char * _metalist_libkcm_knetswitch_la[] = {' > libkcm_knetswitch_la_meta_unload.cpp
	@cat  profiletab.moc knetswitch.moc | grep 'char.*className' | sed -e 's/.*[^A-Za-z0-9_:]\([A-Za-z0-9_:]*\)::className.*$$/\"\1\",/' | sort | uniq >> libkcm_knetswitch_la_meta_unload.cpp
	@echo '0};' >> libkcm_knetswitch_la_meta_unload.cpp
	@echo '#include <kunload.h>' >> libkcm_knetswitch_la_meta_unload.cpp
	@echo '_UNLOAD(libkcm_knetswitch_la)' >> libkcm_knetswitch_la_meta_unload.cpp


#>+ 3
clean-moc-classes:
	-rm -f  libkcm_knetswitch_la_meta_unload.cpp

#>+ 11
libkcm_knetswitch_la.all_cpp.cpp: $(srcdir)/Makefile.in $(srcdir)/profilewidget.cpp $(srcdir)/knetswitch.cpp $(srcdir)/profiletab.cpp $(srcdir)/libkcm_knetswitch_la_meta_unload.cpp   profiletab.moc knetswitch.moc  profiletab.moc
	@echo 'creating libkcm_knetswitch_la.all_cpp.cpp ...'; \
	rm -f libkcm_knetswitch_la.all_cpp.files libkcm_knetswitch_la.all_cpp.final; \
	echo "#define KDE_USE_FINAL 1" >> libkcm_knetswitch_la.all_cpp.final; \
	for file in profilewidget.cpp knetswitch.cpp profiletab.cpp libkcm_knetswitch_la_meta_unload.cpp ; do \
	  echo "#include \"$$file\"" >> libkcm_knetswitch_la.all_cpp.files; \
	  test ! -f $(srcdir)/$$file || egrep '^#pragma +implementation' $(srcdir)/$$file >> libkcm_knetswitch_la.all_cpp.final; \
	done; \
	cat libkcm_knetswitch_la.all_cpp.final libkcm_knetswitch_la.all_cpp.files  > libkcm_knetswitch_la.all_cpp.cpp; \
	rm -f libkcm_knetswitch_la.all_cpp.final libkcm_knetswitch_la.all_cpp.files

#>+ 3
clean-final:
	-rm -f libkcm_knetswitch_la.all_cpp.cpp

#>+ 2
final:
	$(MAKE) libkcm_knetswitch_la_OBJECTS="$(libkcm_knetswitch_la_final_OBJECTS)" all-am
#>+ 2
no-final:
	$(MAKE) libkcm_knetswitch_la_OBJECTS="$(libkcm_knetswitch_la_nofinal_OBJECTS)" all-am
#>+ 3
cvs-clean:
	$(MAKE) -f $(top_srcdir)/admin/Makefile.common cvs-clean

#>+ 3
kde-rpo-clean:
	-rm -f *.rpo

#>+ 4
$(srcdir)/knetswitch.cpp: knetswitch.moc profiletab.h 
$(srcdir)/profilewidget.cpp: profiletab.h 
$(srcdir)/profiletab.cpp: profiletab.moc 
